apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: s3-viewer

servers: 1
agents: 0
image: rancher/k3s:v1.36.2-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 8443:443
    nodeFilters:
      - loadbalancer
registries:
  create:
    name: registry.localhost
    host: 0.0.0.0
    hostPort: "5001"
options:
  k3d:
    wait: true
    timeout: "120s"
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
