apiVersion: v1
kind: Namespace
metadata:
  name: aluminium

---
apiVersion: s3viewer.dev/v1
kind: S3Viewer
metadata:
  name: visionn32
  namespace: aluminium
spec:
  replicas: 1
  accounts:
    - accountKey: BACKUPS
      id: minio-backups
      name: Backups
      endpoint: http://minio-backups.minio.svc.cluster.local:9000
      region: us-east-1
      readOnly: false
      credentialsSecretRef:
        name: minio-backups-creds
        accessKeyKey: access-key
        secretKeyKey: secret-key
    - accountKey: LOGS
      id: minio-logs
      name: Logs
      endpoint: http://minio-logs.minio.svc.cluster.local:9000
      region: us-east-1
      readOnly: false
      credentialsSecretRef:
        name: minio-logs-creds
        accessKeyKey: access-key
        secretKeyKey: secret-key
    - accountKey: ARCHIVE
      id: minio-archive
      name: Archive
      endpoint: http://minio-archive.minio.svc.cluster.local:9000
      region: us-east-1
      readOnly: true
      credentialsSecretRef:
        name: minio-archive-creds
        accessKeyKey: access-key
        secretKeyKey: secret-key
  service:
    port: 3000
    type: ClusterIP
  ingress:
    host: aluminium.127.0.0.1.nip.io
