apiVersion: v1
kind: Namespace
metadata:
  name: aluminium

---
apiVersion: s3viewer.dev/v1
kind: S3Viewer
metadata:
  name: visionn32
  namespace: aluminium
spec:
  replicas: 1
  accounts:
    - accountKey: BACKUPS
      id: s3ScalewayBackup
      name: Backups
      endpoint: https://s3.fr-par.scw.cloud
      region: fr-par
      readOnly: true
      credentialsSecretRef:
        name: scaleway-backups-creds
        accessKeyKey: access-key
        secretKeyKey: secret-key
  service:
    port: 3000
    type: ClusterIP
  ingress:
    host: aluminium.127.0.0.1.nip.io
