apiVersion: v1
kind: Secret
metadata:
  name: minio-backups-creds
  namespace: aluminium
type: Opaque
stringData:
  access-key: minio-backups
  secret-key: minio-backups-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-logs-creds
  namespace: aluminium
type: Opaque
stringData:
  access-key: minio-logs
  secret-key: minio-logs-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-archive-creds
  namespace: aluminium
type: Opaque
stringData:
  access-key: minio-archive
  secret-key: minio-archive-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-media-creds
  namespace: copper
type: Opaque
stringData:
  access-key: minio-media
  secret-key: minio-media-secret

---
apiVersion: v1
kind: Secret
metadata:
  name: minio-archive-creds
  namespace: iron
type: Opaque
stringData:
  access-key: minio-archive
  secret-key: minio-archive-secret
