operator:
  enabled: true
  namespace: s3-viewer
  createNamespace: false
  replicaCount: 1

  image:
    repository: ghcr.io/tchoupinax/s3-viewer-operator
    tag: latest
    pullPolicy: IfNotPresent

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      memory: 256Mi

  serviceAccount:
    create: true
    name: s3-viewer-operator

  rbac:
    create: true

  defaultAppImage: ghcr.io/tchoupinax/s3-viewer:latest

  logLevel: info

  metrics:
    port: 8080

  serviceMonitor:
    enabled: false
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
    labels: {}
    annotations: {}
    relabelings: []
    metricRelabelings: []
