{{- if and .Values.operator.enabled .Values.operator.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "s3-viewer.operator.serviceAccountName" . }}
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "s3-viewer.operator.labels" . | nindent 4 }}
{{- end }}
