apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: s3-viewer-ci
servers: 1
agents: 0
image: rancher/k3s:v1.31.5-k3s1
options:
  k3d:
    wait: true
    timeout: "180s"
  kubeconfig:
    updateDefaultKubeconfig: false
    switchCurrentContext: false
